version: '3.1'
services :
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my-database
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 9090:8080